"use client";
import { useEffect, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { ArrowUpRight, Menu, X } from "lucide-react";
import Link from "next/link";
import { Container } from "@/components/ui/Container";
import { LogoMark } from "@/components/ui/LogoMark";
import { nav } from "@/content/nav";
export function Navbar() { const [scrolled, setScrolled] = useState(false); const [open, setOpen] = useState(false); useEffect(() => { const onScroll = () => setScrolled(window.scrollY > 32); onScroll(); window.addEventListener("scroll", onScroll, { passive: true }); return () => window.removeEventListener("scroll", onScroll); }, []); useEffect(() => { document.body.style.overflow = open ? "hidden" : ""; return () => { document.body.style.overflow = ""; }; }, [open]); return <motion.header initial={{ y: -12, opacity: 0 }} animate={{ y: 0, opacity: 1 }} className="fixed top-0 z-40 w-full"><div className={`transition-all duration-300 ${scrolled ? "border-b border-border bg-bg-dark/90 backdrop-blur-xl" : "bg-transparent"}`}><Container className="flex h-[72px] items-center justify-between"><LogoMark /><nav className="hidden lg:block"><ul className="flex items-center gap-8">{nav.links.map((link) => <li key={link.href}><Link href={link.href} className="text-[13px] text-text-secondary transition-colors hover:text-white">{link.label}</Link></li>)}</ul></nav><Link href={nav.cta.href} className="hidden h-10 items-center gap-2 rounded-[9px] bg-white px-4 text-[13px] font-semibold text-bg-dark transition-colors hover:bg-accent lg:inline-flex">{nav.cta.label}<ArrowUpRight className="h-3.5 w-3.5" /></Link><button type="button" onClick={() => setOpen(!open)} aria-expanded={open} aria-label={open ? "Close menu" : "Open menu"} className="inline-flex h-11 w-11 items-center justify-center text-white lg:hidden">{open ? <X /> : <Menu />}</button></Container></div><AnimatePresence>{open && <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="fixed inset-0 z-50 bg-bg-dark lg:hidden"><Container className="flex h-[72px] items-center justify-between"><LogoMark /><button type="button" onClick={() => setOpen(false)} aria-label="Close menu" className="inline-flex h-11 w-11 items-center justify-center text-white"><X /></button></Container><nav className="px-5 pt-16"><ul className="space-y-7">{nav.links.map((link) => <li key={link.href}><Link href={link.href} onClick={() => setOpen(false)} className="font-display text-[clamp(2.2rem,8vw,4rem)] tracking-[-.05em] text-white">{link.label}</Link></li>)}</ul><Link href={nav.cta.href} onClick={() => setOpen(false)} className="mt-12 inline-flex h-12 items-center gap-2 rounded-[9px] bg-white px-6 text-[14px] font-semibold text-bg-dark">{nav.cta.label}<ArrowUpRight className="h-4 w-4" /></Link></nav></motion.div>}</AnimatePresence></motion.header>; }
